//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_MILK_DATA
    {
        public int CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public System.DateTime MILK_DATE { get; set; }
        public int MILK_TIME { get; set; }
        public int MILK_TYPE { get; set; }
        public float MILK_WEIGHT { get; set; }
        public float MILK_FAT { get; set; }
        public float MILK_SNF { get; set; }
        public float MILK_DEGREE { get; set; }
        public float MILK_RATE { get; set; }
        public float MILK_AMOUNT { get; set; }
    }
}
